package quelle:extension@0.1.0;

use quelle:core/source@0.1.0;
use quelle:core/novel@0.1.0;

interface meta {
    use source.{source-meta};

    extension-info: func () -> source-meta;
    setup: func () -> result<_, string>;
}

interface instance {
    use novel.{novel, chapter-content};

    resource source {
        constructor();
        novel-info: func(url: string) -> result<novel, string>;
        chapter-content: func (url: string) -> result<chapter-content, string>;
    }
}

world extension {
    export meta;
    export instance;
    import quelle:http/main@0.1.0;
}