package quelle:extension@0.1.0;

world extension {
    import source;
    import http;
    import tracing;
    import error;
    import time;

    use source.{source-meta};
    use novel.{novel, chapter-content};
    use error.{error};

    /// Registers the extension with the system.
    export register-extension: func();

    /// The extension meta information.
    export meta: func() -> source-meta;

    /// Initializes the extension.
    export init: func() -> result<_, error>;

    /// Fetches the novel information from the given URL.
    export fetch-novel-info: func(url: string) -> result<novel, error>;

    /// Fetches the chapter content from the given URL.
    export fetch-chapter: func(url: string) -> result<chapter-content, error>;
}
