package quelle:extension@0.1.0;

world extension {
    import source;
    import http;
    import tracing;
    import error;
    import time;

    use source.{source-meta, sort-order};
    use novel.{novel, chapter-content, simple-search-query, complex-search-query, search-result};
    use error.{error};

    /// Registers the extension with the system.
    export register-extension: func();

    /// The extension meta information.
    export meta: func() -> source-meta;

    /// Initializes the extension.
    export init: func() -> result<_, error>;

    /// Fetches the novel information from the given URL.
    export fetch-novel-info: func(url: string) -> result<novel, error>;

    /// Fetches the chapter content from the given URL.
    export fetch-chapter: func(url: string) -> result<chapter-content, error>;

    /// Performs a simple search with just a query string.
    export simple-search: func(query: simple-search-query) -> result<search-result, error>;

    /// Performs a complex search with multiple filters.
    export complex-search: func(query: complex-search-query) -> result<search-result, error>;
}
