interface tracing {
    // Defines a log entry, for general events or messages
    record log-event {
        level: log-level,
        target: string,
        message: string,
        attributes: list<tuple<string, string>>,
        file: option<string>,
        line: option<u32>,
    }

    variant log-level {
        debug,
        info,
        warn,
        error,
        trace,
    }

    // For general log messages, separate from span lifecycle
    on-event: func(event: log-event);
}